### ISSUE TITLE
Fails on remote node without virtualenv

### ISSUE THREAD

**Issue by TauPan** [pytest-dev/pytest-cloud#10]
When I try to run on remote boxes which have the python dependencies installed globally (i.e. *not* in a virtualenv), then pytest-cloud fails with:

```python
delgado@hoots:~AS[1]> py.test --cloud-node=delgado@alekto --cloud-python=/usr/bin/python36                                                 git:(master)  9:56
Detected root dir: /home/delgado/nobackup/git/Customer/myproject
Traceback (most recent call last):
  File "/home/delgado/nobackup/virtualenvs/myproject/bin/py.test", line 8, in <module>
    sys.exit(main())
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/pytest_cloud/plugin.py", line 132, in pytest_cmdline_main
    check_options(config)
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/pytest_cloud/plugin.py", line 329, in check_options
    config=config)
  File "/home/delgado/nobackup/virtualenvs/myproject/lib/python3.6/site-packages/pytest_cloud/plugin.py", line 265, in get_nodes_specs
    **n_m.rsyncoptions)
UnboundLocalError: local variable 'n_m' referenced before assignment
```
(Backtrace slightly redacted via search + replace.)

Note that the *local* code repository has a related virtualenv (as seen in the backtrace) but the remote hosts do not have virtualenvs.

**Comment by bubenkoff** [comment]
the whole idea of pytest-cloud was to not rely on the global dependencies, so please use virtualenv as per documentation
this helps a lot by having a robust, repeatable test suite

**Comment by RonnyPfannschmidt** [comment]
@bubenkoff would it fit to raise a more comprehensible error in case a virtualenv is not used
