### ISSUE TITLE
Getting error  "None of the given test nodes are connectable"

### ISSUE THREAD

**Issue by hah86** [pytest-dev/pytest-cloud#19]
Getting below error when try to execute. I have tested manually **rsync -avz tests/ username@ip:/home/username**  and it works fine.
(workvenv) bash-3.2$ **pytest -m "smoke" --cloud-node=username@IP --cloud-chdir=/home/<username> --cloud-virtualenv-path=<local virtualenv path> --cloud-max-processes=2 --rsyncdir=.**
Detected root dir:<path>
Detecting connectable test nodes...
/Users/harish/Work/workvenv/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/Users/harish/Work/workvenv/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 136, in pytest_cmdline_main
    check_options(config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 335, in check_options
    config=config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 288, in get_nodes_specs
    pytest.exit('None of the given test nodes are connectable')
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/_pytest/outcomes.py", line 85, in exit
    raise Exit(msg, returncode)
_pytest.outcomes.Exit: None of the given test nodes are connectable
(workvenv) bash-3.2$ bash: python3.7: command not found

**Comment by bubenkoff** [comment]
when you pass
--cloud-node=@
what is the intent?
it should be the address

**Comment by hah86** [comment]
Yes, it is  like this --cloud-node=username@IP address of the remote note

**Comment by bubenkoff** [comment]
double-check if the node is connectable via ssh?

**Comment by bubenkoff** [comment]
also, do you see that there's no python3.7 available on the node?

**Comment by hah86** [comment]
Yes, i have checked it, i am able to connect to the node via ssh.
i am passing this parameter so that it picks virtualenv from the local machine **--cloud-virtualenv-path=local virtualenv path**

**Comment by hah86** [comment]
if i do not provide **--cloud-virualenv-path**  below error is thrown

(workvenv) bash-3.2$ pytest tests/ --cloud-node=hramamurthy@10.20.5.6 --cloud-chdir=/home/hramamurthy --cloud-max-processes=2 --rsyncdir=.
Detected root dir: /Users/harish/Work/PPMPro/automation
/Users/harish/Work/workvenv/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/Users/harish/Work/workvenv/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 136, in pytest_cmdline_main
    check_options(config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 335, in check_options
    config=config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 270, in get_nodes_specs
    **n_m.rsyncoptions)
UnboundLocalError: local variable 'n_m' referenced before assignment

**Comment by hah86** [comment]
local machines has python3.7.4 but remote machines has 3.6........does this cause problem ?

**Comment by bubenkoff** [comment]
of course the same python version has to be available on all the nodes

**Comment by bubenkoff** [comment]
but there's also a bug indeed:

if virtualenv_path:
            n_m = NodeManager(config, specs=[])
            virtualenv_path = os.path.relpath(virtualenv_path)

this has to be:

n_m = NodeManager(config, specs=[])
if virtualenv_path:
            virtualenv_path = os.path.relpath(virtualenv_path)


in the pytest_cloud/plugin.py

please submit a PR

**Comment by hah86** [comment]
ok got it .... i will raise a PR

**Comment by hah86** [comment]
i have locally made the changes stated above and still getting this error
_pytest.outcomes.Exit: None of the given test nodes are connectable

**Comment by bubenkoff** [comment]
did you resolve the python version issue on all the nodes?

**Comment by hah86** [comment]
No. i am yet to resolve that issue.
i have raised a PR, please review and merge
