### ISSUE TITLE
Fails with python3 (3.4.4) with raise RuntimeError('parallel is not found.')

### ISSUE THREAD

**Issue by TauPan** [pytest-dev/pytest-cloud#9]
I've tried to find a compatible version of paralel for python3 but couldn't. Is pytest-cloud supposed to be compatible with python3 in general?

```python
> py.test --cloud-nodes delgado@{alekto,{anemoi,aurora}.devel} --cloud-python=/usr/bin/python3                                           git:(master) 11:06
Detected root dir: /home/delgado/projects/Customer/customer-project
Detecting connectable test nodes...
C_GetAttributeValue failed: 48
bind: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 1080
bind: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 15432
bind: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 5672
bind: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 6379
bind: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 15672
Could not request local forwarding.
Warning: remote port forwarding failed for listen port 3128
Found 1 connectable test nodes: {'delgado@alekto'}
RSyncing directory structure
Traceback (most recent call last):
  File "/home/delgado/projects/Customer/customer-project/.venv/bin/py.test", line 10, in <module>
    sys.exit(main())
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/_pytest/config/__init__.py", line 79, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pytest_cloud/plugin.py", line 117, in pytest_cmdline_main
    check_options(config)
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pytest_cloud/plugin.py", line 312, in check_options
    config=config)
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pytest_cloud/plugin.py", line 268, in get_nodes_specs
    rsync.send()
  File "/home/delgado/projects/Customer/customer-project/.venv/lib/python3.4/site-packages/pytest_cloud/rsync.py", line 60, in send
    raise RuntimeError('parallel is not found.')
RuntimeError: parallel is not found.
```

**Comment by marcos-alfredo** [comment]
It's not a Python package, it's a shell utility. I installed it using `yum install parallel`.  
Still got a different error after so not sure yet if the package is compatible with Python 3.

**Comment by bubenkoff** [comment]
@TauPan yes it's a shell utility, install it for you distro
@marcos-alfredo raise an issue with the details

**Comment by TauPan** [comment]
> @TauPan yes it's a shell utility, install it for you distro

This is a documentation issue then. At least I don't see mentioned anywhere that this utility is needed.

**Comment by bubenkoff** [comment]
Please check the readme and if it's not there please open a PR
